// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUdbrkW-hemn-WtLYUNcdjOYxLdzyPWNA',
    appId: '1:975693037757:web:4d40cfea6a1f4b3ee377d4',
    messagingSenderId: '975693037757',
    projectId: 'read-habit',
    authDomain: 'read-habit.firebaseapp.com',
    storageBucket: 'read-habit.firebasestorage.app',
    measurementId: 'G-HH80NX0RGR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjzeg1dJOaE9mVFcVfqfL0XMZcaNZIeig',
    appId: '1:975693037757:android:356e2b2325616d40e377d4',
    messagingSenderId: '975693037757',
    projectId: 'read-habit',
    storageBucket: 'read-habit.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOOJ_zrdLPuaN4f_RcR4YrNSlta5MdGtQ',
    appId: '1:975693037757:ios:cfbe7e460c6313c0e377d4',
    messagingSenderId: '975693037757',
    projectId: 'read-habit',
    storageBucket: 'read-habit.firebasestorage.app',
    iosBundleId: 'com.example.readhabit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOOJ_zrdLPuaN4f_RcR4YrNSlta5MdGtQ',
    appId: '1:975693037757:ios:cfbe7e460c6313c0e377d4',
    messagingSenderId: '975693037757',
    projectId: 'read-habit',
    storageBucket: 'read-habit.firebasestorage.app',
    iosBundleId: 'com.example.readhabit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAUdbrkW-hemn-WtLYUNcdjOYxLdzyPWNA',
    appId: '1:975693037757:web:c3e97b8b48e38935e377d4',
    messagingSenderId: '975693037757',
    projectId: 'read-habit',
    authDomain: 'read-habit.firebaseapp.com',
    storageBucket: 'read-habit.firebasestorage.app',
    measurementId: 'G-P9LX3BFTYY',
  );
}
